const {getOfficer,getAllOfficers,getOfficerHistory,getLeaderboard,changeOfficerPoints}=require('../../database');
const {getGradeFromPoints,getNextGrade,getGradeIndex}=require('../config/grades');
const {getDiscordMember,setMemberGradeRole,sendChannelMessage}=require('./discordService');
const LOG=process.env.LOG_CHANNEL_ID,PROMO=process.env.PROMOTION_CHANNEL_ID,MOD=process.env.DASHBOARD_MODERATOR_ID||'DASHBOARD';
async function enrichOfficer(o){const d=await getDiscordMember(o.user_id),n=getNextGrade(o.points);return {...o,display_name:d.displayName,username:d.username,avatar_url:d.avatarUrl,is_in_server:d.found,joined_at:d.joinedAt,next_grade:n?.name||null,next_grade_points:n?.points||null,points_until_next_grade:n?Math.max(n.points-Number(o.points),0):0};}
async function enrich(list){const out=[];for(let i=0;i<list.length;i+=5)out.push(...await Promise.all(list.slice(i,i+5).map(enrichOfficer)));return out;}
const listOfficers=()=>enrich(getAllOfficers());
const getOfficerProfile=id=>enrichOfficer(getOfficer(id));
const getEnrichedLeaderboard=(limit=25)=>enrich(getLeaderboard(limit));
const getHistory=(id,limit=25)=>getOfficerHistory(id,limit);
async function logChange(m,action,r,oldGrade,newGrade){const add=action==='add';await sendChannelMessage(LOG,{embeds:[{color:add?0x2ecc71:0xe74c3c,title:add?'📈 Ajout de points via Dashboard':'📉 Retrait de points via Dashboard',thumbnail:{url:m.avatarUrl},fields:[{name:'👤 Policier',value:`<@${m.userId}>`,inline:true},{name:'👮 Responsable',value:MOD==='DASHBOARD'?'Dashboard HMPD':`<@${MOD}>`,inline:true},{name:add?'➕ Points ajoutés':'➖ Points retirés',value:String(r.amount),inline:true},{name:'⭐ Ancien total',value:String(r.oldPoints),inline:true},{name:'⭐ Nouveau total',value:String(r.newPoints),inline:true},{name:'🎖️ Grade',value:oldGrade.name===newGrade.name?newGrade.name:`${oldGrade.name} ➜ ${newGrade.name}`,inline:true},{name:'📝 Raison',value:r.reason,inline:false}],timestamp:new Date().toISOString()}],allowed_mentions:{parse:[]}});}
async function modifyOfficerPoints({userId,action,amount,reason}){if(!['add','remove'].includes(action))throw new Error('Action invalide.');if(!Number.isInteger(amount)||amount<1||amount>1000)throw new Error('Le nombre de points doit être compris entre 1 et 1000.');if(typeof reason!=='string'||reason.trim().length<3)throw new Error('La raison doit contenir au moins 3 caractères.');const d=await getDiscordMember(userId,true);if(!d.found)throw new Error("Ce policier n'est plus présent dans le serveur.");const before=getOfficer(userId),oldPoints=Number(before.points),actual=action==='remove'?Math.min(amount,oldPoints):amount,newPoints=action==='add'?oldPoints+actual:oldPoints-actual,oldGrade=getGradeFromPoints(oldPoints),newGrade=getGradeFromPoints(newPoints);await setMemberGradeRole(userId,newGrade.roleId);let result;try{result=changeOfficerPoints({userId,action,amount,grade:newGrade.name,reason:reason.trim(),moderatorId:MOD});}catch(e){await setMemberGradeRole(userId,oldGrade.roleId).catch(()=>{});throw e;}const member=await getDiscordMember(userId,true);await logChange(member,action,{...result,reason:reason.trim()},oldGrade,newGrade).catch(console.error);if(getGradeIndex(newGrade.name)>getGradeIndex(oldGrade.name))await sendChannelMessage(PROMO,{content:`🎉 Félicitations <@${userId}> !`,embeds:[{color:0xf1c40f,title:'🎖️ PROMOTION OFFICIELLE',description:`👤 **Agent :** <@${userId}>\n\n⬆️ **Ancien grade :** ${oldGrade.name}\n\n🏅 **Nouveau grade :** ${newGrade.name}\n\n⭐ **Total des points :** ${result.newPoints}`,timestamp:new Date().toISOString()}],allowed_mentions:{users:[userId],parse:[]}}).catch(console.error);return {result,officer:await getOfficerProfile(userId),oldGrade,newGrade};}
module.exports={listOfficers,getOfficerProfile,getEnrichedLeaderboard,getHistory,modifyOfficerPoints};
