const express=require('express');
const {requireHighCommand}=require('../auth/auth');
const {getManagementSnapshot,getOfficerTimeline,listAudit,getWeeklyReport}=require('../services/managementService');
const router=express.Router();
router.use(requireHighCommand);
router.get('/overview',async(req,res,next)=>{try{res.json({success:true,...await getManagementSnapshot()})}catch(e){next(e)}});
router.get('/officers/:userId/timeline',async(req,res,next)=>{try{res.json({success:true,timeline:await getOfficerTimeline(req.params.userId,req.query.limit)})}catch(e){next(e)}});
router.get('/audit',async(req,res,next)=>{try{res.json({success:true,audit:await listAudit(req.query.limit)})}catch(e){next(e)}});
router.get('/weekly-report',async(req,res,next)=>{try{res.json({success:true,report:await getWeeklyReport()})}catch(e){next(e)}});
module.exports=router;
