const express=require('express');
const {requireHighCommand,getModeratorId}=require('../auth/auth');
const {broadcast}=require('../services/realtimeService');
const {getPromotionProfile,setCriterion,addRpEvaluation,setCaseStatus,approvePromotion,listPromotionCenter}=require('../services/promotionService');
const router=express.Router(); router.use(requireHighCommand);
router.get('/',async(req,res,next)=>{try{res.json({success:true,promotions:await listPromotionCenter(getModeratorId(req))})}catch(e){next(e)}});
router.get('/:userId',async(req,res,next)=>{try{res.json({success:true,promotion:await getPromotionProfile(req.params.userId,getModeratorId(req))})}catch(e){next(e)}});
router.post('/:userId/criteria/:key',async(req,res,next)=>{try{const promotion=await setCriterion({userId:req.params.userId,key:req.params.key,completed:req.body?.completed,note:req.body?.note,actorId:getModeratorId(req)});broadcast('promotion-changed',{userId:req.params.userId});res.json({success:true,promotion})}catch(e){e.publicMessage=e.message;next(e)}});
router.post('/:userId/evaluations',async(req,res,next)=>{try{const evaluation=await addRpEvaluation({userId:req.params.userId,ratings:req.body?.ratings,comment:req.body?.comment,actorId:getModeratorId(req)});broadcast('promotion-changed',{userId:req.params.userId});res.status(201).json({success:true,evaluation})}catch(e){e.publicMessage=e.message;next(e)}});
router.post('/:userId/status',async(req,res,next)=>{try{const promotion=await setCaseStatus({userId:req.params.userId,status:String(req.body?.status||''),reason:req.body?.reason,actorId:getModeratorId(req)});broadcast('promotion-changed',{userId:req.params.userId});res.json({success:true,promotion})}catch(e){e.publicMessage=e.message;next(e)}});
router.post('/:userId/approve',async(req,res,next)=>{try{const promotion=await approvePromotion({userId:req.params.userId,reason:req.body?.reason,actorId:getModeratorId(req)});broadcast('promotion-changed',{userId:req.params.userId});res.json({success:true,message:'Promotion approuvée et rôle Discord mis à jour.',promotion})}catch(e){e.publicMessage=e.message;next(e)}});
module.exports=router;
